### ISSUE TITLE
Response Headers not set

### ISSUE THREAD

**Issue by josephzidell** [didip/tollbooth_gin#2]
@didip Seems that response headers (`X-Rate-Limit-*`) aren't getting sent. Any ideas?

**Comment by didip** [comment]
Good catch. `setResponseHeaders` was never called from `LimitByRequest`.

This is now fixed on Tollbooth `v2.2.0` and the latest `tollbooth_gin`.

See https://github.com/didip/tollbooth/commit/8a5832d289e4375d2fc658ed42ef08975b66dceb and https://github.com/didip/tollbooth_gin/commit/b8e97585488dc711d2756ff5cda889da141cdbdf

**Comment by josephzidell** [comment]
Cool. Thanks
