### ISSUE TITLE
go get fails

### ISSUE THREAD

**Issue by Zamiell** [didip/tollbooth_gin#3]
Steps to reproduce:

1) Install a fresh Ubuntu 16.04
2) Install Go 1.8
3) Execute `go get github.com/didip/tollbooth_gin`

This is the command output:

```
# github.com/didip/tollbooth_gin
src/github.com/didip/tollbooth_gin/tollbooth_gin.go:11: c.Response undefined (type *gin.Context has no field or method Response)
```

Furthermore, I get the same failure on Windows.

**Comment by didip** [comment]
Looks like Gin Context uses `Writer` instead of Response. I think the last commit will fix this.

**Comment by Zamiell** [comment]
Yup it fixed it.

**Comment by Zamiell** [comment]
Except now the example code in the "Five Minutes Tutorial" doesn't compile anymore, complaining that the pointer types don't match for the `tollbooth_gin.LimitHandler` function. Any tips?

By the way, I think it is more grammatically correct to say "Five Minute Tutorial" instead of "Five Minutes Tutorial".

**Comment by didip** [comment]
Try it again? Make sure you update the latest tollbooth_gin

**Comment by Zamiell** [comment]
Works now. Thanks @didip for your support!
